# Generated by Django 5.1.6 on 2025-02-12 11:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParliamentaryConstituencyTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('constituency_name', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartyTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('party', models.CharField(max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.parliamentaryconstituencytable')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.partytable')),
            ],
        ),
        migrations.CreateModel(
            name='VoterTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voterId', models.CharField(max_length=30, unique=True)),
                ('voterName', models.CharField(max_length=30)),
                ('aadhar', models.CharField(max_length=30, null=True)),
                ('mobile', models.CharField(max_length=30)),
                ('voted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.parliamentaryconstituencytable')),
            ],
        ),
        migrations.CreateModel(
            name='EVoteTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.candidatetable')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.votertable')),
            ],
        ),
        migrations.AddField(
            model_name='candidatetable',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.votertable'),
        ),
    ]
