# Generated by Django 5.1.6 on 2025-02-12 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evotetable',
            name='voter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voting.votertable'),
        ),
    ]
